name: Build static site

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build static Pelican site
        uses: nelsonjchen/gh-pages-pelican-action@0.1.7
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
